import { Inter } from "next/font/google";
import "./globals.css";
import MaterialThemeProvider from "@/components/MaterialThemeProvider";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deep Docs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <MaterialThemeProvider>
        <html lang="en">
          <head>
            <link rel="icon" href="/Row-Doc.svg" />
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
          </head>
          <body className={inter.className}>{children}</body>
        </html>
      </MaterialThemeProvider>
    </SessionWrapper>
  );
}
